---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  resources:
  - name: source
    type: git
  tasks:
  - name: hello
    taskRef:
      name: message
      kind: ClusterTask
    params:
    - name: name
      value: DevOps Toolkit
  - name: goodbye
    runAfter:
     - hello
    taskRef:
      name: goodbye
      kind: ClusterTask
  - name: ci
    taskRef:
      name: ci
      kind: ClusterTask
    resources:
      inputs:
      - name: source
        resource: source
