---

# TODO: Remove
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: message
spec:
  params:
  - name: name
    type: string
    description: What is your name?
  steps:
  - name: write-message
    image: ubuntu
    script: |
      echo "Hello $(params.name)! How are you?" \
        | tee /workspace/message
  - name: read-message
    image: ubuntu
    command:
    - cat
    args:
    - /workspace/message

---

# TODO: Remove
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: goodbye
spec:
  steps:
  - name: goodbye
    image: ubuntu
    script: |
      #!/bin/bash
      echo "Goodbye everyone!"

---

apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ci
spec:
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: clone
    image: ubuntu
    script: |
      ls -la $(inputs.resources.source.path)
